package edu.uob.utils;

public enum ErrorType {
    DATABASE_NOT_FOUND_EXCEPTION("DATABASE NOT FOUND."),
    DUPLICATE_DATABASE_CREATION_EXCEPTION("DATABASE NAME ALREADY IN USE. FAILED TO CREATE DATABASE."),
    DATABASE_CREATION_FAILED_EXCEPTION("FAILED TO CREATE DATABASE."),
    DUPLICATE_TABLE_CREATION_EXCEPTION("TABLE NAME ALREADY IN USE. FAILED TO CREATE TABLE."),
    CLOSE_DATABASE_EXCEPTION("FAILED TO CLOSE DATABASE."),
    DELETE_DATABASE_EXCEPTION("FAILED TO DELETE DATABASE"),
    TABLE_NOT_FOUND_EXCEPTION("TABLE NOT FOUND."),
    TABLE_CREATION_FAILED_EXCEPTION("FAILED TO CREATE TABLE."),
    LOAD_TABLE_EXCEPTION("FAILED TO LOAD TABLE."),
    INVALID_PRIMARY_KEY_EXCEPTION("KEY NOT FOUND. PRIMARY KEY IS INVALID."),
    INVALID_ATTRIBUTE_EXCEPTION("ATTRIBUTE NOT FOUND. INVALID KEY"),
    DUPLICATE_ATTRIBUTE_EXCEPTION("ATTRIBUTE NAME ALREADY IN USE. FAILED TO ADD ATTRIBUTE TO TABLE"),
    INVALID_QUERY_EXCEPTION("QUERY COULD NOT BE PARSED. VIOLATES BNF."),
    INVALID_ACTION_TYPE("ALTER COMMAND CAN ONLY ADD OR DROP. NO OTHER ACTIONS ARE SUPPORTED."),
    NO_DATABASE_IN_USE("INVALID QUERY: NO DATABASE IN USE. TO SELECT A DATABASE ISSUE THE COMMAND 'SQL:> USE [DATABASE_NAME]'"),
    INVALID_LIST_EXCEPTION("INVALID ATTRIBUTE LIST."),
    INVALID_VALUE_EXCEPTION("INVALID VALUE."),
    PK_DROP_EXCEPTION("PRIMARY KEY CANNOT BE DROPPED");

    private final String message;
    private ErrorType(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}

